#!/bin/sh

case "$1" in
	start)
		printf "usbserial.ko modules: "
		insmod /lib/modules/usbserial.ko vendor=0x04b4 product=0x02f8
		[ $? = 0 ] && echo "OK" || echo "FAIL"

		;;
	stop)

		;;
	restart|reload)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit 0
